name: Build GTFS feeds

on:
  schedule:
    - cron: '20 03 * * *'
  workflow_dispatch:  # Manual trigger from GitHub UI
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: List files in working directory
      run: ls -l
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Print working directory
      run: pwd
    
    - name: Run Python script
      env:
        TranzyGithubBuildKey: ${{secrets.TRANZYGITHUBBUILDKEY}}
      run: python FetchAndConvert.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Add all changes
        git add .

        # Commit changes with timestamp
        git commit -m "Update GTFS feeds for $(TZ=Europe/Bucharest date +'%d %B %Y %H:%M')" || echo "No changes to commit"

        # Push changes
        git push origin HEAD:${{ github.ref }}
