name: Test
on:
  workflow_dispatch:  # Manual trigger from GitHub UI
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: List files in working directory
      run: ls -l
    - name: List files in Output directory
      run: ls -l Output
